### ISSUE TITLE
Enemy mockups

### ISSUE THREAD

**Issue by thewongdylan** [thewongdylan/dyf-orbital#28]

**Comment by thewongdylan** [comment]
done: air (wizard), earth (golem)

**Comment by yihfei** [comment]
fire and air enemies mockup
![wizard preview](https://github.com/thewongdylan/dyf-orbital/assets/89378503/9754b403-977e-4b66-adfc-be0b77429da7)
![devil preview](https://github.com/thewongdylan/dyf-orbital/assets/89378503/77f5b324-c5a3-4992-894b-a98987f39bc8)
