### ISSUE TITLE
Fire Level

### ISSUE THREAD

**Issue by thewongdylan** [thewongdylan/dyf-orbital#40]

**Comment by yihfei** [comment]
<img width="453" alt="Screenshot 2023-06-25 at 6 45 19 PM" src="https://github.com/thewongdylan/dyf-orbital/assets/89378503/a11307ce-78b3-492a-abf3-c7b6c5d7765c">
<img width="394" alt="Screenshot 2023-06-25 at 6 46 09 PM" src="https://github.com/thewongdylan/dyf-orbital/assets/89378503/225b26bc-01c5-4e28-b96d-ad65c3221660">
fire and air stage
