### ISSUE TITLE
readme pictures

### ISSUE THREAD

**Issue by yihfei** [thewongdylan/dyf-orbital#41]
<img width="837" alt="Screenshot 2023-06-24 at 4 10 27 PM" src="https://github.com/thewongdylan/dyf-orbital/assets/89378503/9fe9d9c1-d3b4-4214-87bc-0a46e6d25c4b">
<img width="789" alt="Screenshot 2023-06-24 at 4 37 51 PM" src="https://github.com/thewongdylan/dyf-orbital/assets/89378503/da79d2fb-e078-4ba3-8e25-1223fb4bc0eb">
<img width="342" alt="Screenshot 2023-06-24 at 4 36 22 PM" src="https://github.com/thewongdylan/dyf-orbital/assets/89378503/547681f4-76d0-406c-8204-1b8b42b13921">
<img width="830" alt="Screenshot 2023-06-24 at 4 30 49 PM" src="https://github.com/thewongdylan/dyf-orbital/assets/89378503/3a245b95-f885-4684-9eb4-1d5d2f64f961">

**Comment by thewongdylan** [comment]
![Class Diagram (1)](https://github.com/thewongdylan/dyf-orbital/assets/90192310/a0893dd2-411c-4d0f-9353-616c5b15bc15)

**Comment by thewongdylan** [comment]
[Class Diagram.pdf](https://github.com/thewongdylan/dyf-orbital/files/11862875/Class.Diagram.pdf)

**Comment by thewongdylan** [comment]
![Class Diagram](https://github.com/thewongdylan/dyf-orbital/assets/90192310/f45f2ef5-511a-4fac-9388-3a0202ea2f67)
